<<<<<<< HEAD
var venues = [{"name":"Muhammad Ali Center","VenueID":"4b3134f0f964a5209b0225e3","Description":"The Muhammad Ali Center is a multicultural center with an award-winning museum dedicated to the life of Muhammad Ali. The Center museum captures the inspiration derived from the story of Muhammad Ali’s incredible life and the six core principles that have fueled his journey.","Address":"144 N 6th St, Louisville, KY 40202","Hours":null,"Photo":"http://www.soulofamerica.com/phpwcms/picture/upload/Image/us_cities/Black_Museums/Lou_Muhammad_Ali_Center.jpg","Category":"history","beenHere":0,"badgeLink":"/img/art.svg"},
{"name":"Kentucky Museum of Art and Craft (KMAC)","VenueID":"4b6cb984f964a520594f2ce3","Description":"\nThe Kentucky Museum of Art and Craft is a non profit organization that supports and promotes excellence in art, craft, applied arts and design.","Address":"715 West Main Street, Louisville, KY 40202","Hours":null,"Photo":"http://www.whyquiltsmatter.org/welcome/wp-content/gallery/image-resources-episode-3-the-quilt-marketplace/marketplace_80.jpg","Category":"art & culture","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Churchill Downs","VenueID":"4b0933a7f964a520b31423e3","Description":"Churchill Downs racetrack -- home of the famed Kentucky Derby -- remains the flagship operation of Churchill Downs Incorporated, and recently underwent the most significant series of ambitious and comprehensive renovations in the history of the track","Address":"700 Central Ave, Louisville, KY 40208","Hours":null,"Photo":"http://farm1.staticflickr.com/228/487750004_ee9db59fbf_z.jpg","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Joe Huber's Family Farm & Rest.","VenueID":"4c003dadf61ea5938592eb13","Description":" Huber's Family Produce Farm is now managed by 3rd generation farmers, Steve and Ethel Huber since the retirement of George and June Huber in 1991.  Kids can enjoy hayrides, ","Address":"2421 Engle Road Starlight, Indiana 47106","Hours":null,"Photo":"http://4.bp.blogspot.com/-FSlMqseeeL4/UkomvstcdCI/AAAAAAAAGqI/1ZuSYLmUcrk/s1600/Joe+Huber's+Sept+2013+(22).JPG","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Louisville Slugger Museum & Factory","VenueID":"4b4261d2f964a520c3d225e3","Description":"Louisville Slugger Museum & Factory is a fun, exciting and educational day away from the classroom. See the world’s tallest bat and learn about the bat making process from forest to factory. ","Address":"800 W Main St, Louisville, KY 40202","Hours":null,"Photo":"http://brokensidewalk.com/wp-content/uploads/2012/01/rollin_stanley_lou_17.jpg","Category":"history","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Belle of Louisville","VenueID":"4ba7d023f964a5208fb539e3","Description":"There's something about the sound of the whistle, the turn of the paddlewheel, and the running of steam engines built in the late 1800s that captivates the imagination. Children of all ages feel a connection almost as soon as they get on board. ","Address":"401 West River Road Louisville, KY","Hours":null,"Photo":"http://farm1.staticflickr.com/11/16815019_48064d4ff2_z.jpg","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Cave Hill National Cemetery","VenueID":"4b0948a1f964a520351523e3","Description":"Cave Hill Cemetery is more than a sacred resting place. It is an integral part of the legacy of the Louisville community. Its stewardship has been entrusted to successive generations for over 160 years and now is your time. There are five different tours: Historical Walking Tour, Twilight Tram Tour, Horticultural, Art and Artists, and Civil War Tour","Address":"701 Baxter Ave, Louisville, KY 40204","Hours":null,"Photo":"http://farm1.staticflickr.com/123/340100820_88585048b3_z.jpg?zz=1","Category":"art & culture","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Kentucky Derby Museum","VenueID":"4bc517cf6c26b71302edeaf3","Description":"The Kentucky Derby Museum, which sits on the front steps of historic Churchill Downs, is a very visible part of our community as one of Louisville’s premiere attractions. Graciously welcoming over 210,000 guests through the doors each year and giving them a first hand look at the event for which Louisville, Kentucky is known worldwide.","Address":"704 Central Ave, Louisville, KY 40208","Hours":null,"Photo":"http://derbyexperiences.com/assets/resources/26/large/Derby-Experiences-Kentucky-Derby-History-of-the-Kentucky-Derby-Garland-of-Roses-at-Kentucky-Derby-Museum.jpg","Category":"art & culture","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Kentucky Science Center","VenueID":"4b6d8c07f964a520c57b2ce3","Description":"The man-made cavern spans under a number of roadways above and is part of 17 miles of corridors located beneath the city of Louisville, Kentucky.","Address":"727 West Main Street, Louisville, KY 40202","Hours":null,"Photo":"http://www.worldofstock.com/slides/ADT6924.jpg","Category":"science","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Louisville Mega Cavern","VenueID":"4b146795f964a5209ea223e3","Description":"The man-made cavern spans under a number of roadways above and is part of 17 miles of corridors located beneath the city of Louisville, Kentucky.","Address":"1841 Taylor Ave,\nLouisville, KY 40213","Hours":null,"Photo":"http://d27q2wygkjta99.cloudfront.net/megacaverns/images/logo.png","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"}]
=======
var venues = [{"name":"Muhammad Ali Center","VenueID":"4b3134f0f964a5209b0225e3","Description":"The Muhammad Ali Center is a multicultural center with an award-winning museum dedicated to the life of Muhammad Ali. The Center museum captures the inspiration derived from the story of Muhammad Ali’s incredible life and the six core principles that have fueled his journey.","Hours":null,"Photo":"http://www.soulofamerica.com/phpwcms/picture/upload/Image/us_cities/Black_Museums/Lou_Muhammad_Ali_Center.jpg","Category":"history","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Kentucky Museum of Art and Craft (KMAC)","VenueID":"4b6cb984f964a520594f2ce3","Description":"\nThe Kentucky Museum of Art and Craft is a non profit organization that supports and promotes excellence in art, craft, applied arts and design.","Hours":null,"Photo":"http://www.whyquiltsmatter.org/welcome/wp-content/gallery/image-resources-episode-3-the-quilt-marketplace/marketplace_80.jpg","Category":"art & culture","beenHere":0,"badgeLink":"/img/art.svg"},
{"name":"Churchill Downs","VenueID":"4b0933a7f964a520b31423e3","Description":"Churchill Downs racetrack -- home of the famed Kentucky Derby -- remains the flagship operation of Churchill Downs Incorporated, and recently underwent the most significant series of ambitious and comprehensive renovations in the history of the track","Hours":null,"Photo":"http://farm1.staticflickr.com/228/487750004_ee9db59fbf_z.jpg","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Joe Huber's Family Farm & Rest.","VenueID":"4c003dadf61ea5938592eb13","Description":" Huber's Family Produce Farm is now managed by 3rd generation farmers, Steve and Ethel Huber since the retirement of George and June Huber in 1991.  Kids can enjoy hayrides, ","Hours":null,"Photo":"http://4.bp.blogspot.com/-FSlMqseeeL4/UkomvstcdCI/AAAAAAAAGqI/1ZuSYLmUcrk/s1600/Joe+Huber's+Sept+2013+(22).JPG","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Louisville Slugger Museum & Factory","VenueID":"4b4261d2f964a520c3d225e3","Description":"Louisville Slugger Museum & Factory is a fun, exciting and educational day away from the classroom. See the world’s tallest bat and learn about the bat making process from forest to factory. ","Hours":null,"Photo":"http://brokensidewalk.com/wp-content/uploads/2012/01/rollin_stanley_lou_17.jpg","Category":"history","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Belle of Louisville","VenueID":"4ba7d023f964a5208fb539e3","Description":"There's something about the sound of the whistle, the turn of the paddlewheel, and the running of steam engines built in the late 1800s that captivates the imagination. Children of all ages feel a connection almost as soon as they get on board. ","Hours":null,"Photo":"http://farm1.staticflickr.com/11/16815019_48064d4ff2_z.jpg","Category":"outdoors","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Cave Hill National Cemetery","VenueID":"4b0948a1f964a520351523e3","Description":"Cave Hill Cemetery is more than a sacred resting place. It is an integral part of the legacy of the Louisville community. Its stewardship has been entrusted to successive generations for over 160 years and now is your time. There are five different tours: Historical Walking Tour, Twilight Tram Tour, Horticultural, Art and Artists, and Civil War Tour","Hours":null,"Photo":"http://farm1.staticflickr.com/123/340100820_88585048b3_z.jpg?zz=1","Category":"art & culture","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Kentucky Derby Museum","VenueID":"4bc517cf6c26b71302edeaf3","Description":"The Kentucky Derby Museum, which sits on the front steps of historic Churchill Downs, is a very visible part of our community as one of Louisville’s premiere attractions. Graciously welcoming over 210,000 guests through the doors each year and giving them a first hand look at the event for which Louisville, Kentucky is known worldwide.","Hours":null,"Photo":"http://derbyexperiences.com/assets/resources/26/large/Derby-Experiences-Kentucky-Derby-History-of-the-Kentucky-Derby-Garland-of-Roses-at-Kentucky-Derby-Museum.jpg","Category":"art & culture","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Kentucky Science Center","VenueID":"4b6d8c07f964a520c57b2ce3","Description":"The man-made cavern spans under a number of roadways above and is part of 17 miles of corridors located beneath the city of Louisville, Kentucky.","Hours":null,"Photo":"http://www.worldofstock.com/slides/ADT6924.jpg","Category":"science","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"},
{"name":"Louisville Mega Cavern","VenueID":"4b146795f964a5209ea223e3","Description":"The man-made cavern spans under a number of roadways above and is part of 17 miles of corridors located beneath the city of Louisville, Kentucky.","Hours":null,"Photo":"http://d27q2wygkjta99.cloudfront.net/megacaverns/images/logo.png","Category":"","beenHere":0,"badgeLink":"/img/US_Marshal_Badge.png"}]
>>>>>>> 111863160eacd72281fe1edb402e4b2a7d9c1c46
